[libraries]
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckonPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[versions]
icu4j = "71.1"
jmhPlugin = "0.6.8"
junit = "5.9.1"
lombokPlugin = "6.5.1"
reckonPlugin = "0.16.1"
versionsPlugin = "0.43.0"
