[libraries]
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckonPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[versions]
icu4j = "71.1"
junit = "4.13.2"
lombokPlugin = "6.4.3.1"
reckonPlugin = "0.13.1"
versionsPlugin = "0.42.0"
